import type { Metadata } from "next";
import { Inter, Lato, Unbounded } from "next/font/google";
import { Montserrat_Subrayada as MontserratSubrayada } from "next/font/google";
import "./globals.css";
import { StarknetProvider } from "@/components/StarknetProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const fontMontserratSubrayada = MontserratSubrayada({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-montserrat-subrayada",
});

const fontLato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
});

const fontUnbounded = Unbounded({
  subsets: ["latin"],
  variable: "--font-unbounded",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${fontMontserratSubrayada.variable} ${fontLato.variable} ${fontUnbounded.variable}`}
      >
        <StarknetProvider>{children}</StarknetProvider>
      </body>
    </html>
  );
}
